/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as AppTaskRouteRouteImport } from './routes/app/task/route'
import { Route as AppProjectsRouteRouteImport } from './routes/app/projects/route'
import { Route as AppBoardRouteRouteImport } from './routes/app/board/route'
import { Route as AppTaskIndexRouteImport } from './routes/app/task/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppExamplesIndexRouteImport } from './routes/app/examples/index'
import { Route as AppBoardIndexRouteImport } from './routes/app/board/index'
import { Route as AppappIndexRouteImport } from './routes/app/(app)/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTaskTaskIdRouteRouteImport } from './routes/app/task/$taskId/route'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects/$projectId/route'
import { Route as AppTaskTaskIdIndexRouteImport } from './routes/app/task/$taskId/index'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const AppTaskRouteRoute = AppTaskRouteRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRouteRoute = AppProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardRouteRoute = AppBoardRouteRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTaskIndexRoute = AppTaskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTaskRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRouteRoute,
} as any)
const AppExamplesIndexRoute = AppExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardIndexRoute = AppBoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardRouteRoute,
} as any)
const AppappIndexRoute = AppappIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaskTaskIdRouteRoute = AppTaskTaskIdRouteRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTaskRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppProjectsRouteRoute,
  } as any)
const AppTaskTaskIdIndexRoute = AppTaskTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTaskTaskIdRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteRouteWithChildren
  '/app/projects': typeof AppProjectsRouteRouteWithChildren
  '/app/task': typeof AppTaskRouteRouteWithChildren
  '/': typeof landingIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/task/$taskId': typeof AppTaskTaskIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/app/': typeof AppappIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/examples/': typeof AppExamplesIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/task/': typeof AppTaskIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/task/$taskId/': typeof AppTaskTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/app': typeof AppappIndexRoute
  '/app/board': typeof AppBoardIndexRoute
  '/app/examples': typeof AppExamplesIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/task': typeof AppTaskIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/task/$taskId': typeof AppTaskTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(landing)': typeof landingRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteRouteWithChildren
  '/app/projects': typeof AppProjectsRouteRouteWithChildren
  '/app/task': typeof AppTaskRouteRouteWithChildren
  '/(landing)/': typeof landingIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/task/$taskId': typeof AppTaskTaskIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/app/(app)/': typeof AppappIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/examples/': typeof AppExamplesIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/task/': typeof AppTaskIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/task/$taskId/': typeof AppTaskTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/board'
    | '/app/projects'
    | '/app/task'
    | '/'
    | '/app/projects/$projectId'
    | '/app/task/$taskId'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/app/'
    | '/app/board/'
    | '/app/examples/'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/task/'
    | '/app/projects/$projectId/'
    | '/app/task/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/app'
    | '/app/board'
    | '/app/examples'
    | '/app/projects'
    | '/app/settings'
    | '/app/task'
    | '/app/projects/$projectId'
    | '/app/task/$taskId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(landing)'
    | '/app'
    | '/app/board'
    | '/app/projects'
    | '/app/task'
    | '/(landing)/'
    | '/app/projects/$projectId'
    | '/app/task/$taskId'
    | '/api/auth/$'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/app/(app)/'
    | '/app/board/'
    | '/app/examples/'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/task/'
    | '/app/projects/$projectId/'
    | '/app/task/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  landingRouteRoute: typeof landingRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/app/task': {
      id: '/app/task'
      path: '/task'
      fullPath: '/app/task'
      preLoaderRoute: typeof AppTaskRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/task/': {
      id: '/app/task/'
      path: '/'
      fullPath: '/app/task/'
      preLoaderRoute: typeof AppTaskIndexRouteImport
      parentRoute: typeof AppTaskRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/app/examples/': {
      id: '/app/examples/'
      path: '/examples'
      fullPath: '/app/examples/'
      preLoaderRoute: typeof AppExamplesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/board/': {
      id: '/app/board/'
      path: '/'
      fullPath: '/app/board/'
      preLoaderRoute: typeof AppBoardIndexRouteImport
      parentRoute: typeof AppBoardRouteRoute
    }
    '/app/(app)/': {
      id: '/app/(app)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppappIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/task/$taskId': {
      id: '/app/task/$taskId'
      path: '/$taskId'
      fullPath: '/app/task/$taskId'
      preLoaderRoute: typeof AppTaskTaskIdRouteRouteImport
      parentRoute: typeof AppTaskRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/app/task/$taskId/': {
      id: '/app/task/$taskId/'
      path: '/'
      fullPath: '/app/task/$taskId/'
      preLoaderRoute: typeof AppTaskTaskIdIndexRouteImport
      parentRoute: typeof AppTaskTaskIdRouteRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface AppBoardRouteRouteChildren {
  AppBoardIndexRoute: typeof AppBoardIndexRoute
}

const AppBoardRouteRouteChildren: AppBoardRouteRouteChildren = {
  AppBoardIndexRoute: AppBoardIndexRoute,
}

const AppBoardRouteRouteWithChildren = AppBoardRouteRoute._addFileChildren(
  AppBoardRouteRouteChildren,
)

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppProjectsRouteRouteChildren {
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteRouteChildren: AppProjectsRouteRouteChildren = {
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteRouteWithChildren =
  AppProjectsRouteRoute._addFileChildren(AppProjectsRouteRouteChildren)

interface AppTaskTaskIdRouteRouteChildren {
  AppTaskTaskIdIndexRoute: typeof AppTaskTaskIdIndexRoute
}

const AppTaskTaskIdRouteRouteChildren: AppTaskTaskIdRouteRouteChildren = {
  AppTaskTaskIdIndexRoute: AppTaskTaskIdIndexRoute,
}

const AppTaskTaskIdRouteRouteWithChildren =
  AppTaskTaskIdRouteRoute._addFileChildren(AppTaskTaskIdRouteRouteChildren)

interface AppTaskRouteRouteChildren {
  AppTaskTaskIdRouteRoute: typeof AppTaskTaskIdRouteRouteWithChildren
  AppTaskIndexRoute: typeof AppTaskIndexRoute
}

const AppTaskRouteRouteChildren: AppTaskRouteRouteChildren = {
  AppTaskTaskIdRouteRoute: AppTaskTaskIdRouteRouteWithChildren,
  AppTaskIndexRoute: AppTaskIndexRoute,
}

const AppTaskRouteRouteWithChildren = AppTaskRouteRoute._addFileChildren(
  AppTaskRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppBoardRouteRoute: typeof AppBoardRouteRouteWithChildren
  AppProjectsRouteRoute: typeof AppProjectsRouteRouteWithChildren
  AppTaskRouteRoute: typeof AppTaskRouteRouteWithChildren
  AppappIndexRoute: typeof AppappIndexRoute
  AppExamplesIndexRoute: typeof AppExamplesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBoardRouteRoute: AppBoardRouteRouteWithChildren,
  AppProjectsRouteRoute: AppProjectsRouteRouteWithChildren,
  AppTaskRouteRoute: AppTaskRouteRouteWithChildren,
  AppappIndexRoute: AppappIndexRoute,
  AppExamplesIndexRoute: AppExamplesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  landingRouteRoute: landingRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
